name: Debricked scan

on: [push]    

jobs:
  debricked:
    runs-on: ubuntu-latest

    container:
      image: debricked/cli:latest-resolution-debian

    steps:    
     - uses: actions/checkout@v3    
     - uses: debricked/actions/callgraph@v3
     - run: |
          ls
     - run: |
          cat debricked-call-graph.java
     - run: |
          cat maven.debricked.lock
          
     - uses: debricked/actions@v3
     
       env:
          DEBRICKED_TOKEN: 'e4e2d2b7231276c02b667fc9493422050f0160c0843e779e'
          DEBRICKED_URI: 'https://review-6831-reach-qc4gm9.review.debricked.dev'
