name: Debricked scan

on: [push]    

jobs:
  debricked:
    runs-on: ubuntu-latest

    container:
      image: debricked/cli:latest-resolution-debian

    steps:    
     - uses: actions/checkout@v3    
     - uses: debricked/actions/callgraph@v3
     - run: |
          ls     
     - uses: debricked/actions@v3
     - run: |
          cat debricked-call-graph.java
       env:
          DEBRICKED_TOKEN: '8cd656437bee8b0004242d1911278706531079ad28dbfc00'
          DEBRICKED_URI: 'https://review-6831-reach-qc4gm9.review.debricked.dev'
