name: Debricked scan

on: [push]

jobs: 
 vulnerabilities-scan-review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: debricked/actions/callgraph@v4
      - run: |
          ls
      - uses: debricked/actions@v4
        env:
          DEBRICKED_TOKEN: '63b780621440b7f3c3d20bf594116b6bd312afdef406ab2c'
          DEBRICKED_URI: 'https://review-6831-reach-qc4gm9.review.debricked.dev'
          
 vulnerabilities-scan-staging:
  runs-on: ubuntu-latest

  steps:
      - uses: actions/checkout@v4
      - uses: debricked/actions/callgraph@v4
      - run: |
          ls
      - uses: debricked/actions@v4
        env:
          DEBRICKED_TOKEN: 'fe4dcd64c911285a06cd40b5e7c68dce2206ba289ccc6d6e'
          DEBRICKED_URI: 'https://staging.debricked.com'

 vulnerabilities-scan-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: debricked/actions/callgraph@v4
      - run: |
          ls
      - uses: debricked/actions@v4
        env:
          DEBRICKED_TOKEN: 'b822ebb82caaff4a2f909293ded90589317ddcf100e04eec'
          DEBRICKED_URI: 'https://debricked.com'
