name: Debricked scan

on: [push]

jobs:
 

  vulnerabilities-scan-review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: debricked/actions/callgraph@v4
      - run: |
          ls
      - uses: debricked/actions@v4
        env:
          DEBRICKED_TOKEN: 'ef5fdac3c418b789ff810f31b36906d74a42ff5b641096ae'
          DEBRICKED_URI: 'https://review-6831-reach-qc4gm9.review.debricked.dev'  
