name: Debricked scan

on: [push]    

jobs:
  debricked:
    runs-on: ubuntu-latest

    container:
      image: debricked/cli:latest-resolution-debian

    steps:    
     - uses: actions/checkout@v3
     - run: |
          rm /.debrickedTmpFolder
     - uses: debricked/actions/callgraph@v4
     - run: |
          ls     
     - uses: debricked/actions@v3
       env:
          DEBRICKED_TOKEN: 'cd3d45d852eebee4b5897d16722cf8b99e21d49c43e73707'
          DEBRICKED_URI: 'https://review-6831-reach-qc4gm9.review.debricked.dev'
