name: Debricked scan

on: [push]

jobs:
  vulnerabilities-scan-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: debricked/actions/callgraph@v3
      - uses: debricked/actions@v3
        env:
          DEBRICKED_TOKEN: '5e83c45986d159fe7764ed4391c0405493d3287aa8eb796d'

  vulnerabilities-scan-staging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: debricked/actions/callgraph@v3
      - uses: debricked/actions@v3
        env:
          DEBRICKED_TOKEN: 'e1656ccfa4d1f4787b281d6d06a6f7e3d9adb5206b941944'
          DEBRICKED_URI: 'https://staging.debricked.com'

  vulnerabilities-scan-review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: debricked/actions/callgraph@v3
      - run: |
          ls
      - uses: debricked/actions@v3
        env:
          DEBRICKED_TOKEN: '2eaa60d16219f48813a899c4362aff3ed2b5b4efeb09116f'
          DEBRICKED_URI: 'https://review-6831-reach-qc4gm9.review.debricked.dev'  
